version: 1.0.{build}
image: Visual Studio 2019

install:
  - ps: Install-Product node 14
  - cmd: npm install -g npm

before_build:
  - cmd: if not exist "C:\Users\appveyor\AppData\Roaming\npm" mkdir "C:\Users\appveyor\AppData\Roaming\npm"
  - ps: |
      if (!(Test-Path -Path "C:\Users\appveyor\AppData\Roaming\npm")) {
          New-Item -ItemType Directory -Path "C:\Users\appveyor\AppData\Roaming\npm"
      }

build_script:
  - cmd: npm install
  - cmd: npm run build
  - cmd: npm run lint
  - cmd: npm test

after_test:
  - cmd: npx push-dir --dir=dist --branch=gh-pages --force --verbose